PCCMathSAC/orcca

- src/section-solving-linear-equations-and-inequalities-with-fractions.mbx
Carl: please review this edit of what we discussed on 2/1
> changed intro by removing fraction rules and adding introductory exposition

- src/section-solving-linear-equations-and-inequalities-with-fractions.mbx
Carl: These are the changes to the examples that we discussed. Please review them. I think that one more example with a non-integer solution is now needed; let me know your thoughts.
> changed examples so that the constants and solutions are more varied

- src/section-graphing-equations.mbx
No major changes. Still editing work to do on exercises.
(I'll spend time on alternate introductory example this week.)
> Edits to expository content for readability and clarity

- src/section-solving-system-equations-by-substitution.mbx
Alex: I have read through Rob Beezer's url info, but I'm doing something wrong with the links in the intro example I'm working on.
> working on intro; have errors with hyperlinks

- src/section-solving-system-equations-by-elimination.mbx
- src/section-solving-system-equations-by-substitution.mbx
All: That last example was originally only a one variable problem. I changed it to be two variable, but it might be too contrived now.
Carl: The exercises that I added from the MTH 60 mixing section have solutions that use tables instead of systems of equations. Can you change these, or let me know where they exist if they already do?
Carl/Alex: There are two WW problems that do not appear to be working:
BasicAlgebra/SystemsOfLinearEquations/SystemOfEquations13.pg
BasicAlgebra/SystemsOfLinearEquations/SystemOfEquations14.pg
> finished last exercise; added exercises from old MTH 60 mixing section

- src/section-factoring-out-the-common-factor.ptx
Further notes/questions:
1. The only example with two variables ends up being prime. Should there be one simpler example with two variables (like 5xy^2-10xy) and then a prime example that doesn't involve two variables?
2. Minor: there's an alignment issue in the side by side within an algorithm.
> minor edits/typos

- src/section-factoring-by-grouping.ptx
- src/section-factoring-trinomials-with-a-nontrivial-leading-coefficient.ptx
- src/section-factoring-trinomials-with-leading-coefficient-one.ptx
Once the multi-variable polynomials situation is cleared up, this may get more revision in the text. Also at that point I will review the exercises in this section and the gcf section. This section needs more exercises either way --- I'll double up WeBWorK problems then.
> edits to factoring by grouping

- src/section-absolute-value-and-square-root.ptx
- src/section-factoring-by-grouping.ptx
- src/section-factoring-special-polynomials.ptx
- src/section-factoring-trinomials-with-a-nontrivial-leading-coefficient.ptx
- src/section-factoring-trinomials-with-leading-coefficient-one.ptx
Ann, if you have a chance to approve this, I can officially hand the chapter off to Ross.
There is still a place holder for a "factoring review" section. I have two thoughts on this.
1. I'd like at least Ross to review and sign off on the primary sections first before writing a review.
2. Personally I think there should just be one review section here. As opposed to a section that discusses how to strategize and then another section that behaves like our reviews from chapters 1--4. The strategies discussion will get in enough review examples all in one place. I get it that this messes with the symmetry of the nature of previous review sections, but I don't think that would be worth the paper, not to mention the time spent writing another section.
> revisions to special facotring patterns

- src/chapter-factoring.ptx
- src/section-solving-systems-of-linear-equations-by-graphing.ptx
The next thing I will do will be to work on this section's exercises. Most of them need to be converted to non-WeBWorK.
> revisions to solving systems by graphing

- src/review-basic-math-review.ptx
- src/review-variables-expressions-and-equations.ptx
- src/section-completing-the-square-and-vertex-form.ptx
- src/section-dividing-polynomials.ptx
- src/section-exponent-rules-and-scientific-notation.ptx
- src/section-factoring-by-grouping.ptx
- src/section-factoring-out-the-common-factor.ptx
- src/section-factoring-trinomials-with-leading-coefficient-one.ptx
- src/section-graphing-quadratic-functions.ptx
- src/section-introduction-to-exponent-rules.ptx
- src/section-introduction-to-radical-functions.ptx
- src/section-multiplying-polynomials.ptx
- src/section-negative-exponents.ptx
- src/section-slope-intercept-form.ptx
- src/section-solving-multistep-linear-equations-and-inequalities.ptx
- src/section-special-cases-of-multiplying-polynomials.ptx
> Edits for polynomial chapter

- src/section-solving-systems-of-linear-equations-by-graphing.ptx
Alex: The comment regarding adding an application from MTH 60 was from me. (Which points out that I should write -aec when leaving anything like that). I like the way that application reads now and wouldn't change it. The background of that comment is that we originally had a lot of the "do this 2-variable system problem but just with one variable" problems in MTH 60, which generally are done with tables to get around using two variables. We cut them from MTH 60 after talking with the SAC, and for the most part put them into the systems section of MTH 65.
> typos, removed commented out comment regarding changing modeling problem

- src/section-factoring-special-polynomials.ptx
- src/section-factoring-trinomials-with-a-nontrivial-leading-coefficient.ptx
Better more diverse numerical values for ac method. Proof got hid in an example that they are encouraged to skip until later.
> cleaned up non-monic section, hid proof

- src/appendix-ccogs.ptx
- src/section-completing-the-square-and-vertex-form.ptx
- src/section-exponent-rules-and-scientific-notation.ptx
- src/section-rationalizing-denominator.ptx
- src/section-scientific-notation.ptx
- src/section-solving-quadratic-equations-by-using-a-square-root.ptx
- src/section-solving-radical-equations.ptx
- src/section-square-root-properties.ptx
I found one or two things in one section and did a larger search to find more misspellings.
> typos that I randomly found

- src/section-graphing-quadratic-functions.ptx
I keyed the first two static exercises for the subset of exercises and outlined the others. See "Sketching Graphs of Quadratic Functions." 
I plan to key the remaining ones tonight. Can someone look over the problem statements and first two keyed problems and comment on two things:
1. Is depth/breadth/variety ok? I went for the odd/even pattern we've aimed for in some instances.
2. Should there be more explanation? (Eg showing the algebra for how an intercept was determined?)
-Ann
> outlined remaining static exercises; not yet keyed

- src/review-factoring.ptx
- src/section-factoring-special-polynomials.ptx
I'm still working on the factoring flow chart... Dealing with details. Hopefully done by Nov 10.
> tiny edit to special factoring and creation of factoring review

- src/review-factoring.ptx
- src/section-exploring-two-variable-data-and-rate-of-change.ptx
- src/section-slope-intercept-form.ptx
- src/section-slope.ptx
- src/section-special-solution-sets.ptx
Biggest change is a new subsection about writing the slope intercept form of an equation given two points. Someone should definitely read through it carefully and add some WW exercises below. R
> a couple of edits via the report form

- src/section-solving-quadratic-equations-by-factoring.ptx
- src/section-solving-quadratic-equations-by-using-a-square-root.ptx
- src/section-square-root-properties.ptx
- src/section-the-quadratic-formula.ptx
Minor edits to factoring and square root properties sections
Major edits to solving with square roots and quadratic formula
Moved all complex solutions to new section
> edits to solving quadratics sections

- src/review-graphing-lines.ptx
- src/section-absolute-value-and-square-root.ptx
- src/section-introduction-to-functions.ptx
- src/section-solving-systems-of-linear-equations-by-graphing.ptx
I need someone to look through my additions and clean them up. I already asked Ann if she would do that since she worked on this section most recently.
R
> a few typos in sections and edits to functions section

- src/section-solving-quadratic-equations-by-factoring.ptx
- src/section-square-root-properties.ptx
> added application and cleaned up solving by factoring

- src/section-graphing-quadratic-functions.ptx
- src/section-introduction-to-functions.ptx
- src/section-properties-of-quadratic-functions.ptx
added more description to domain and range in 9.1, added domain and range subsections in 9.2 and 9.3
> added domain and range to quad functions

- src/bookinfo.ptx
And several merge commits dealing with weird stuff.
> Added unhighlight

- src/section-using-technology-to-explore-functions.ptx
Cara: I'll proofread these with fresh eyes tomorrow morning, and then they'll be ready to be looked over.
> the second half of the exercises for technology section

- src/section-comparison-symbols-and-notation-for-intervals.ptx
Alex: I'm finished with this section, so go ahead and address the WW notation.
Maybe more pressing though, there appears to be different WW/ image issue. The first checkpoint and last checkpoint in this section appear swapped in the html file. Their code appears correct. I did:
make webwork-extraction
make merge
make images
make html
> edits to merged comparison symbol and interval notation section

- src/appendix-geometry.ptx
- src/frontmatter.ptx
- src/review-basic-math-review.ptx
- src/review-graphing-lines.ptx
- src/section-absolute-value-and-square-root.ptx
- src/section-absolute-value-equations-and-inequalities.ptx
- src/section-addition-and-subtraction-of-rational-expressions.ptx
- src/section-cartesian-coordinates.ptx
- src/section-completing-the-square.ptx
added image descriptions and minor edits
> added image descriptions

- src/review-basic-math-review.ptx
- src/review-systems-of-linear-equations.ptx
- src/section-substitution.ptx
Again,  could go into master, I just didn't think about it. This fix doesn't affect anyone's learning.
> alignment issues in substitution systems

- src/review-basic-math-review.ptx
- src/review-graphing-lines.ptx
- src/review-linear-equations-and-inequalities.ptx
- src/review-variables-expressions-and-equations.ptx
Severla make CHeck errors and substantial edits to graphing lines review.
> Various edits to edition.

- src/review-absolute-value-functions.ptx
- src/review-radical-functions-and-equations.ptx
- src/review-rational-functions-and-equations.ptx
- src/section-introduction-to-radical-functions.ptx
- src/section-radical-expressions-and-rational-exponents.ptx
fixed xrefs in chapter 11 and 13 reviews and other minor edits
> Chapter 14 review and minor edits

- src/section-addition-and-subtraction-of-rational-expressions.ptx
- src/section-complex-fractions.ptx
- src/section-introduction-to-radical-functions.ptx
- src/section-more-on-rationalizing-the-denominator.ptx
- src/section-multiplication-and-division-of-rational-expressions.ptx
- src/section-radical-expressions-and-rational-exponents.ptx
- src/section-solving-radical-equations.ptx
- src/section-solving-rational-equations.ptx
Note: there are more review and warmup exercises in the sections on multiplying/dividing rational expressions, as well as adding/subtracting rational expressions. (16-20 instead of 8-12). This is intentional as it's such a rough topic for students.
> remaining ch 13 review and warmup exercises

- src/section-review-of-graphing.ptx
- src/section-solving-equations-and-inequalities-graphically.ptx
Alex: More exercises of the same kind need to be added to the end of the review of graphing exercises but I don't know your pg code. I tried to emulate it a bit, but it started getting buggy. Could you copy and paste a couple more like that last one for some more radicals, cubics, rationals and maybe some exponentials? Thanks.
> added exercises to review-of-graphing

- src/review-quantities-in-the-physical-world.ptx
- src/section-geometry-applications.ptx
- src/section-geometry-formulas.ptx
This is the correct pull request -  I hope!
> geometry application section and related changes
